#!/usr/bin/env bash

if [-z "which asdf" ]; then
	echo "installing asdf"
	brew install asdf

	asdf plugin add nodejs
	asdf install nodejs latest
	asdf global nodejs latest

	asdf plugin add ruby
	asdf install ruby latest
	asdf global ruby latest

	asdf plugin golang
	asdf install golang latest
	asdf global golang latest
else
	echo "asdf already installed"
fi
