#!/usr/bin/env bash

if ! command -v asdf > /dev/null 2>&1; then
	echo "Installing asdf"
	brew install libyaml
	brew install asdf
else
	echo "asdf already installed"
fi

languages=(
	"nodejs"
	"ruby"
	"golang"
	"rust"
)

for lang in "${languages[@]}"
do
	if ! asdf plugin list | grep -q "$lang"; then
		if [[ "$lang" == "nodejs" || "$lang" == "ruby" ]]; then
			echo "Adding plugin $lang..."
			asdf plugin add "$lang"
		else
			echo "Adding plugin $lang from GitHub URL https://github.com/asdf-community/asdf-$lang.git ..."
			asdf plugin add "$lang" "https://github.com/asdf-community/asdf-$lang.git"
		fi
	else
		echo "Plugin, $lang already added."
	fi

	echo "Installing $lang version latest"
	asdf install "$lang" latest

	echo "Setting default $lang version to latest"
	asdf set -u "$lang" latest
done
