#!/usr/bin/env bash

if ! command -v devbox > /dev/null 2>&1; then
	echo "installing devbox"
	curl -fsSL https://get.jetify.com/devbox | bash
	cd ~/.devbox-environments/claude
	devbox install
else
	echo "devbox already installed"
fi
